version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:${CIRCLE_BUILD_NUM} .
      - run:
          name: Save Docker image
          command: docker save -o image.tar $IMAGE_NAME:${CIRCLE_BUILD_NUM}
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  push:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $IMAGE_NAME:${CIRCLE_BUILD_NUM}

workflows:
  build:
    jobs:
      - build
      - push:
          requires:
            - build
