version: 2.1

orbs:
  node: circleci/node@5.1

workflows:
  build-and-test:
    jobs:
      - build:
          executor: node/default
          steps:
            - checkout
            - node/install
            - run: npm run build
            - persist_to_workspace:
                root: ~/project
                paths:
                  - .
