version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t my-app .
