version: 2.1

orbs:
  node: circleci/node@5.1
jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
