version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:${CIRCLE_BUILD_NUM} .

  push:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:${CIRCLE_BUILD_NUM}

workflows:
  build:
    jobs:
      - build
      - push:
          requires:
            - build
