version: 2.1

orbs:
  node: circleci/node@5.2.1

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
